version: '3.8'
services:
  app:
    build:
      args:
        user: gug4
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: poc-clean-arch-with-tests-php
    image: gugaferri/poc-clean-arch-with-tests-php
    working_dir: /var/www
    volumes:
      - .:/var/www/
    networks:
      - poc-clean-arch-with-tests

  nginx:
    image: nginx:latest
    container_name: poc-clean-arch-with-tests-nginx
    ports:
      - 8111:80
    volumes:
      - .:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - poc-clean-arch-with-tests

networks:
  poc-clean-arch-with-tests:
    name: poc-clean-arch-with-tests
    driver: bridge